### ISSUE TITLE
AirPlay2 support

### ISSUE THREAD

**Issue by hojo0590** [hifiberry/extension_shairport#1]
Hi there,

I'm watching your current efforts moving the different soruces to extensions (which imho seems a good thing to do). While trying out building your latest `hifiberry-os` development branch I noticed that AirPlay stopped working as before.  
I hope I'm not interfering with your current efforts, but it seems building `shairport-sync` for the extension happens without AirPlay2 support 

https://github.com/hifiberry/extension_shairport/blob/62d3daac98f15f0bc22eebc79cef15d96f905db1/Dockerfile.shairport-sync#L27-L36

unlike the `shairport-sync` project does for their [Dockerfile using `--with-airplay-2` flag](https://github.com/mikebrady/shairport-sync/blob/d5d984303a88917be80927f65cc0531da30f9e9c/docker/Dockerfile#L58-L61).  

Are you going to continue supporting `AirPlay2`? (You also building an `nqptp` container could be suggesting so...)

And as I'm currently tampering with the docker container provided by `shairport-sync` with the new extensible `HifiBerryOS` - trying to understand what what does - you might be able to tell me if I could ever succeed using the official `shaiport-sync` docker container instead of this extension, or if there is something in the way I don't see yet.

**Comment by hojo0590** [comment]
Had a first success - a docker-compose.yml
```yaml
version: '3'

services:
  shairport-sync:
    container_name: shairport-sync
    restart: always
    image: mikebrady/shairport-sync:latest
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /etc/shairport-sync.conf:/etc/shairport-sync.conf
      - /etc/asound.conf:/etc/asound.conf
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    # Set max open file limit to avoid memory allocation issues: https://github.com/mikebrady/shairport-sync/issues/1756#issuecomment-1826803898
    # Limits possibly not perfect - simply taken from https://docs.docker.com/compose/compose-file/05-services/#ulimits
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
```
let's the `HifiBerry` be found again in `Apple Home`. Yet any music requested via Siri _does_ play but _does not_ yet show up with the artist and song title in the web UI...
